
/*
 *  vcs_cmds.c
 *
 *  This file is automatically generated on Wed May 28 18:02:03 2014
 *  DO NOT modify this file!!!
 */

#include <stddef.h>

#include "vcs_cmds.h"

#define MAKE_DEFAULT_VALUE(x)   ((void *)(x))

static osa_cmd_arg_t vcs_cmd_vcs_settime_args[6] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "y",
		.m_name       = "Year",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "m",
		.m_name       = "Month",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "d",
		.m_name       = "Day",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "h",
		.m_name       = "Hour",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "i",
		.m_name       = "Minute",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "s",
		.m_name       = "Second",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_setnetparams_args[3] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "ip",
		.m_name       = "address",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "nm",
		.m_name       = "netmask",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "gw",
		.m_name       = "gateway",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_setdbglevel_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "l",
		.m_name       = "level",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_getstrmparam_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "channel id(0-4)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_setstrmparam_args[5] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "channel id(0-4)",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "w",
		.m_name       = "width",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "h",
		.m_name       = "height",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "r",
		.m_name       = "frame rate",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "b",
		.m_name       = "bitrate",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_getstrminfo_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "channel id(0-4)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_disablevencchn_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "channel id(0-4)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_enablevencchn_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "channel id(0-4)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_setbitrate_args[2] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "channel id(0-4)",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "b",
		.m_name       = "bitrate",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_reqidr_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "t",
		.m_name       = "stream type",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_createvdecchn_args[13] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "cid",
		.m_name       = "channel id(0-15)",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "wid",
		.m_name       = "window id(0-15)",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "dev",
		.m_name       = "output dev id(0-3)",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "w",
		.m_name       = "max width",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "h",
		.m_name       = "max height",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "r",
		.m_name       = "frame rate",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "b",
		.m_name       = "bitrate",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "c",
		.m_name       = "codecs",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "m",
		.m_name       = "field merge decode enable",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "t",
		.m_name       = "transport type",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "port",
		.m_name       = "remote port",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "ip",
		.m_name       = "remote ip",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_STRING,
		.m_tag        = "url",
		.m_name       = "rtsp url",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_deletevdecchn_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "channel id(0-15)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_disablevdecchn_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "channel id(0-15)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_enablevdecchn_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "channel id(0-15)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_changevdecsource_args[5] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "channel id(0-15)",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "t",
		.m_name       = "transport type",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "port",
		.m_name       = "remote port",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "ip",
		.m_name       = "remote ip",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_STRING,
		.m_tag        = "url",
		.m_name       = "rtsp url",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_switchlayout_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "mode",
		.m_name       = "layout mode(0-9)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_switchwindows_args[3] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "dev",
		.m_name       = "output dev id(0-3)",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id1",
		.m_name       = "window id1(0-15)",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id2",
		.m_name       = "window id2(0-15)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_disablewindow_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "window id(0-15)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t vcs_cmd_vcs_enablewindow_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "id",
		.m_name       = "window id(0-15)",
		.m_required   = 1,
	},
};

osa_cmd_t glb_vcs_cmds[VCS_CMDS_NUM] = 
{
	{
		.m_id         = VCS_VDEV_CMD_GET_TIME,
		.m_cmd        = "vcs_gettime",
		.m_description = "Get vcs system time.",
		.m_access     = OSA_CMD_ACCESS_ADMIN,
		.m_nargs      = 0,
		.m_args       = NULL,
	},
	{
		.m_id         = VCS_VDEV_CMD_SET_TIME,
		.m_cmd        = "vcs_settime",
		.m_description = "Set vcs system time.",
		.m_access     = OSA_CMD_ACCESS_ADMIN,
		.m_nargs      = 6,
		.m_args       = vcs_cmd_vcs_settime_args,
	},
	{
		.m_id         = VCS_VDEV_CMD_GET_NETPARAMS,
		.m_cmd        = "vcs_getnetparams",
		.m_description = "Get vcs system network configuration.",
		.m_access     = OSA_CMD_ACCESS_ADMIN,
		.m_nargs      = 0,
		.m_args       = NULL,
	},
	{
		.m_id         = VCS_VDEV_CMD_SET_NETPARAMS,
		.m_cmd        = "vcs_setnetparams",
		.m_description = "Set vcs system network configuration.",
		.m_access     = OSA_CMD_ACCESS_ADMIN,
		.m_nargs      = 3,
		.m_args       = vcs_cmd_vcs_setnetparams_args,
	},
	{
		.m_id         = VCS_VDEV_CMD_KEEP_ALIVE,
		.m_cmd        = "vcs_keepalive",
		.m_description = "Vcs system network keep alive.",
		.m_access     = OSA_CMD_ACCESS_ADMIN,
		.m_nargs      = 0,
		.m_args       = NULL,
	},
	{
		.m_id         = VCS_VDEV_CMD_REBOOT,
		.m_cmd        = "vcs_reboot",
		.m_description = "Reboot vcs system.",
		.m_access     = OSA_CMD_ACCESS_ADMIN,
		.m_nargs      = 0,
		.m_args       = NULL,
	},
	{
		.m_id         = VCS_VSYS_CMD_PRINT_TASK_STATS,
		.m_cmd        = "vcs_taskstats",
		.m_description = "Print system task statistics.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 0,
		.m_args       = NULL,
	},
	{
		.m_id         = VCS_VSYS_CMD_PRINT_THDP_STATS,
		.m_cmd        = "vcs_thdpstats",
		.m_description = "Print system thdp statistics.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 0,
		.m_args       = NULL,
	},
	{
		.m_id         = VCS_VSYS_CMD_PRINT_DVRMOD_STATS,
		.m_cmd        = "vcs_dvrmodstats",
		.m_description = "Print dvr rdk modules statistics.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 0,
		.m_args       = NULL,
	},
	{
		.m_id         = VCS_VSYS_CMD_PRINT_DVRBUF_STATS,
		.m_cmd        = "vcs_dvrbufstats",
		.m_description = "Print dvr rdk buffer statistics.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 0,
		.m_args       = NULL,
	},
	{
		.m_id         = VCS_VSYS_CMD_PRINT_IVDHD_STATS,
		.m_cmd        = "vcs_ivahdstats",
		.m_description = "Print dvr rdk ivahd statistics.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 0,
		.m_args       = NULL,
	},
	{
		.m_id         = VCS_VSYS_CMD_SET_DEBUG_LEVEL,
		.m_cmd        = "vcs_setdbglevel",
		.m_description = "Set vcs system debug level.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_setdbglevel_args,
	},
	{
		.m_id         = VCS_VENC_CMD_GET_STREAM_PARAM,
		.m_cmd        = "vcs_getstrmparam",
		.m_description = "Vcs encode channel get stream params.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_getstrmparam_args,
	},
	{
		.m_id         = VCS_VENC_CMD_SET_STREAM_PARAM,
		.m_cmd        = "vcs_setstrmparam",
		.m_description = "Vcs encode channel set stream params.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 5,
		.m_args       = vcs_cmd_vcs_setstrmparam_args,
	},
	{
		.m_id         = VCS_VENC_CMD_GET_STREAM_INFO,
		.m_cmd        = "vcs_getstrminfo",
		.m_description = "Vcs encode channel get stream infomation.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_getstrminfo_args,
	},
	{
		.m_id         = VCS_VENC_CMD_DISABLE_CHANNEL,
		.m_cmd        = "vcs_disablevencchn",
		.m_description = "Disable encode channel temporary.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_disablevencchn_args,
	},
	{
		.m_id         = VCS_VENC_CMD_ENABLE_CHANNEL,
		.m_cmd        = "vcs_enablevencchn",
		.m_description = "Enable encode channel.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_enablevencchn_args,
	},
	{
		.m_id         = VCS_VENC_CMD_SET_BITRATE,
		.m_cmd        = "vcs_setbitrate",
		.m_description = "Set encode channle bitrate dynamically.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 2,
		.m_args       = vcs_cmd_vcs_setbitrate_args,
	},
	{
		.m_id         = VCS_VENC_CMD_REQUEST_IDR,
		.m_cmd        = "vcs_reqidr",
		.m_description = "Vcs encode request idr frame.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_reqidr_args,
	},
	{
		.m_id         = VCS_VDEC_CMD_CREATE_CHANNEL,
		.m_cmd        = "vcs_createvdecchn",
		.m_description = "Create decode channel dynamically.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 13,
		.m_args       = vcs_cmd_vcs_createvdecchn_args,
	},
	{
		.m_id         = VCS_VDEC_CMD_DELETE_CHANNEL,
		.m_cmd        = "vcs_deletevdecchn",
		.m_description = "Delete decode channel dynamically.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_deletevdecchn_args,
	},
	{
		.m_id         = VCS_VDEC_CMD_DISABLE_CHANNEL,
		.m_cmd        = "vcs_disablevdecchn",
		.m_description = "Disable decode channel temporary.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_disablevdecchn_args,
	},
	{
		.m_id         = VCS_VDEC_CMD_ENABLE_CHANNEL,
		.m_cmd        = "vcs_enablevdecchn",
		.m_description = "Enable decode channel.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_enablevdecchn_args,
	},
	{
		.m_id         = VCS_VDEC_CMD_CHANGE_SOURCE,
		.m_cmd        = "vcs_changevdecsource",
		.m_description = "Change decode channel source dynamically.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 5,
		.m_args       = vcs_cmd_vcs_changevdecsource_args,
	},
	{
		.m_id         = VCS_VDIS_CMD_SWITCH_LAYOUT,
		.m_cmd        = "vcs_switchlayout",
		.m_description = "Switch display layout.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_switchlayout_args,
	},
	{
		.m_id         = VCS_VDIS_CMD_SWITCH_WINDOWS,
		.m_cmd        = "vcs_switchwindows",
		.m_description = "Switch two windows.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 3,
		.m_args       = vcs_cmd_vcs_switchwindows_args,
	},
	{
		.m_id         = VCS_VDIS_CMD_DISABLE_WINDOW,
		.m_cmd        = "vcs_disablewindow",
		.m_description = "Disable window.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_disablewindow_args,
	},
	{
		.m_id         = VCS_VDIS_CMD_ENABLE_WINDOW,
		.m_cmd        = "vcs_enablewindow",
		.m_description = "Enable window.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = vcs_cmd_vcs_enablewindow_args,
	},
};

/* generated file vcs_cmds.c ends. */
