################################################################################
#
#	The makefile for red light 500w project.
#
################################################################################

# include local Rules.mak
#-include Rules.mak
CC	   :=gcc
#CC	   :=armv5tle-gsv-linuxeabi-gcc

TARGET := $(notdir $(CURDIR))

CPU_TYPE :=

VERBOSE :=true
ifeq ($(VERBOSE), true)
	override VERBOSE =
else
	override VERBOSE = @
endif

INCLUDE    := -I"include"

#MACRO_LIST += -DIMAGE_FILE
#MACRO_LIST += -DVEHDET_GLPR

C_FLAGS  += $(INCLUDE) #-O2
LD_FLAGS += -lpthread -lm -lrt
#LD_FLAGS += -shared -fpic

# Modules subdirectory
UTILS_MODULE	:= src
RTSP_MODULE		:= test

# The source files
SOURCES := $(wildcard $(UTILS_MODULE)/*.c)				\
		   $(wildcard $(RTSP_MODULE)/*.c)

# The header files.
HEADERS := $(wildcard $(UTILS_MODULE)/*.h)				\
		   $(wildcard $(RTSP_MODULE)/*.h)

COMPILE.c := $(VERBOSE) $(CC) $(C_FLAGS) $(CPP_FLAGS) $(MACRO_LIST)
LINK.c    := $(VERBOSE) $(CC) $(LD_FLAGS)

# The object files.
OBJFILES 	 := $(SOURCES:%.c=%.o)

# The library file.
#EXEC_FILE  := $(addprefix main_, $(strip $(TARGET)))
#EXEC_FILE  := threadpool_test_demo
LIB_FILE	:= tsk_mgr_main

.PHONY : all clean

all: $(TARGET)

$(TARGET): PRINTMSG $(LIB_FILE)
	$(VERBOSE) echo
	$(VERBOSE) echo Finished to build $(TARGET) module.
	$(VERBOSE) echo
 
PRINTMSG:
	$(VERBOSE) echo Begin to build $(TARGET) module...

$(LIB_FILE): $(OBJFILES)
	$(VERBOSE) $(LINK.c) -o $@  $^
	
$(OBJFILES): %.o: %.c $(HEADERS)
	$(VERBOSE) $(COMPILE.c) -o $@ -c $< 

clean:
	@echo Removing files generated by compiler...
	$(VERBOSE) $(RM) -rf $(OBJFILES) $(LIB_FILE)
	@echo Finished to remove files generated by compiler.

#
# The end of makefile.
#
