
/*
 *  module_cmds.c
 *
 *  This file is automatically generated on Mon Jan 20 14:14:19 2014
 *  DO NOT modify this file!!!
 */

#include "module_cmds.h"

#define MAKE_DEFAULT_VALUE(x)   ((void *)(x))

static osa_cmd_arg_t module_cmd_createchn_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "c",
		.m_name       = "Channel ID (0-15)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t module_cmd_deletechn_args[1] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "c",
		.m_name       = "Channel ID (0-15)",
		.m_required   = 1,
	},
};

static osa_cmd_arg_t module_cmd_setbitrate_args[2] = 
{
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "c",
		.m_name       = "Channel ID (0-15)",
		.m_required   = 1,
	},
	{
		.m_type       = OSA_CMD_ARG_UNSIGNED,
		.m_tag        = "r",
		.m_name       = "Bitrate (500Kb-8000Kb)",
		.m_required   = 1,
	},
};

osa_cmd_t glb_module_cmds[MODULE_CMDS_NUM] = 
{
	{
		.m_id         = MODULE_CMD_CREATE_CHANNEL,
		.m_cmd        = "createchn",
		.m_description = "Create module channel.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = module_cmd_createchn_args,
	},
	{
		.m_id         = MODULE_CMD_DELETE_CHANNEL,
		.m_cmd        = "deletechn",
		.m_description = "Delete module channel.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 1,
		.m_args       = module_cmd_deletechn_args,
	},
	{
		.m_id         = MODULE_CMD_SET_BITRATE,
		.m_cmd        = "setbitrate",
		.m_description = "Set module channel bit rate.",
		.m_access     = OSA_CMD_ACCESS_USER,
		.m_nargs      = 2,
		.m_args       = module_cmd_setbitrate_args,
	},
};

/* generated file module_cmds.c ends. */
