
/*
 *  vcs_cmds.h
 *
 *  This file is automatically generated on Wed May 28 18:02:03 2014
 *  DO NOT modify this file!!!
 */

#ifndef __VCS_CMDS_H
#define __VCS_CMDS_H

#include "osa_cmd.h"


/* vcs command codes */

#define VCS_VDEV_CMD_GET_TIME                            100
#define VCS_VDEV_CMD_SET_TIME                            101
#define VCS_VDEV_CMD_GET_NETPARAMS                       102
#define VCS_VDEV_CMD_SET_NETPARAMS                       103
#define VCS_VDEV_CMD_KEEP_ALIVE                          104
#define VCS_VDEV_CMD_REBOOT                              105
#define VCS_VSYS_CMD_PRINT_TASK_STATS                    106
#define VCS_VSYS_CMD_PRINT_THDP_STATS                    107
#define VCS_VSYS_CMD_PRINT_DVRMOD_STATS                  108
#define VCS_VSYS_CMD_PRINT_DVRBUF_STATS                  109
#define VCS_VSYS_CMD_PRINT_IVDHD_STATS                   110
#define VCS_VSYS_CMD_SET_DEBUG_LEVEL                     111
#define VCS_VENC_CMD_GET_STREAM_PARAM                    120
#define VCS_VENC_CMD_SET_STREAM_PARAM                    121
#define VCS_VENC_CMD_GET_STREAM_INFO                     122
#define VCS_VENC_CMD_DISABLE_CHANNEL                     123
#define VCS_VENC_CMD_ENABLE_CHANNEL                      124
#define VCS_VENC_CMD_SET_BITRATE                         125
#define VCS_VENC_CMD_REQUEST_IDR                         126
#define VCS_VDEC_CMD_CREATE_CHANNEL                      140
#define VCS_VDEC_CMD_DELETE_CHANNEL                      141
#define VCS_VDEC_CMD_DISABLE_CHANNEL                     142
#define VCS_VDEC_CMD_ENABLE_CHANNEL                      143
#define VCS_VDEC_CMD_CHANGE_SOURCE                       144
#define VCS_VDIS_CMD_SWITCH_LAYOUT                       160
#define VCS_VDIS_CMD_SWITCH_WINDOWS                      161
#define VCS_VDIS_CMD_DISABLE_WINDOW                      162
#define VCS_VDIS_CMD_ENABLE_WINDOW                       163

#define VCS_CMDS_NUM                                      28

extern osa_cmd_t glb_vcs_cmds[VCS_CMDS_NUM];

#define VCS_VDEV_CMD_SET_TIME_ARG_y                        0
#define VCS_VDEV_CMD_SET_TIME_ARG_m                        1
#define VCS_VDEV_CMD_SET_TIME_ARG_d                        2
#define VCS_VDEV_CMD_SET_TIME_ARG_h                        3
#define VCS_VDEV_CMD_SET_TIME_ARG_i                        4
#define VCS_VDEV_CMD_SET_TIME_ARG_s                        5
#define VCS_VDEV_CMD_SET_NETPARAMS_ARG_ip                  0
#define VCS_VDEV_CMD_SET_NETPARAMS_ARG_nm                  1
#define VCS_VDEV_CMD_SET_NETPARAMS_ARG_gw                  2
#define VCS_VSYS_CMD_SET_DEBUG_LEVEL_ARG_l                 0
#define VCS_VENC_CMD_GET_STREAM_PARAM_ARG_id               0
#define VCS_VENC_CMD_SET_STREAM_PARAM_ARG_id               0
#define VCS_VENC_CMD_SET_STREAM_PARAM_ARG_w                1
#define VCS_VENC_CMD_SET_STREAM_PARAM_ARG_h                2
#define VCS_VENC_CMD_SET_STREAM_PARAM_ARG_r                3
#define VCS_VENC_CMD_SET_STREAM_PARAM_ARG_b                4
#define VCS_VENC_CMD_GET_STREAM_INFO_ARG_id                0
#define VCS_VENC_CMD_DISABLE_CHANNEL_ARG_id                0
#define VCS_VENC_CMD_ENABLE_CHANNEL_ARG_id                 0
#define VCS_VENC_CMD_SET_BITRATE_ARG_id                    0
#define VCS_VENC_CMD_SET_BITRATE_ARG_b                     1
#define VCS_VENC_CMD_REQUEST_IDR_ARG_t                     0
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_cid                0
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_wid                1
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_dev                2
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_w                  3
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_h                  4
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_r                  5
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_b                  6
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_c                  7
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_m                  8
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_t                  9
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_port              10
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_ip                11
#define VCS_VDEC_CMD_CREATE_CHANNEL_ARG_url               12
#define VCS_VDEC_CMD_DELETE_CHANNEL_ARG_id                 0
#define VCS_VDEC_CMD_DISABLE_CHANNEL_ARG_id                0
#define VCS_VDEC_CMD_ENABLE_CHANNEL_ARG_id                 0
#define VCS_VDEC_CMD_CHANGE_SOURCE_ARG_id                  0
#define VCS_VDEC_CMD_CHANGE_SOURCE_ARG_t                   1
#define VCS_VDEC_CMD_CHANGE_SOURCE_ARG_port                2
#define VCS_VDEC_CMD_CHANGE_SOURCE_ARG_ip                  3
#define VCS_VDEC_CMD_CHANGE_SOURCE_ARG_url                 4
#define VCS_VDIS_CMD_SWITCH_LAYOUT_ARG_mode                0
#define VCS_VDIS_CMD_SWITCH_WINDOWS_ARG_dev                0
#define VCS_VDIS_CMD_SWITCH_WINDOWS_ARG_id1                1
#define VCS_VDIS_CMD_SWITCH_WINDOWS_ARG_id2                2
#define VCS_VDIS_CMD_DISABLE_WINDOW_ARG_id                 0
#define VCS_VDIS_CMD_ENABLE_WINDOW_ARG_id                  0

#endif /* __VCS_CMDS_H */
