
/*
 * osa_status.c
 *
 * This file is automatically generated on Tue Jul 28 12:04:26 2015
 * DO NOT modify this file!
 *
 */

#include "osa_status.h"
 
static osa_status_descp_t glb_status_descps[OSA_STATUS_DESCP_NUM] =
{
	{
		.m_id = OSA_SOK,
		.m_msg = "Success.",
	},
	{
		.m_id = OSA_EFAIL,
		.m_msg = "General failure.",
	},
	{
		.m_id = OSA_EMEM,
		.m_msg = "Out of memory.",
	},
	{
		.m_id = OSA_ENOENT,
		.m_msg = "No such entry.",
	},
	{
		.m_id = OSA_EARGS,
		.m_msg = "Invalid argument.",
	},
	{
		.m_id = OSA_EINVAL,
		.m_msg = "Invalid value.",
	},
	{
		.m_id = OSA_EEXIST,
		.m_msg = "Entry already eixst.",
	},
	{
		.m_id = OSA_ERES,
		.m_msg = "No enough resource.",
	},
	{
		.m_id = OSA_EPERM,
		.m_msg = "Operation no permitted.",
	},
	{
		.m_id = OSA_ECONNECT,
		.m_msg = "Network connect error.",
	},
	{
		.m_id = OSA_ETIMEOUT,
		.m_msg = "I/O timeout.",
	},
	{
		.m_id = OSA_EEOF,
		.m_msg = "Reach the end of file.",
	},
	{
		.m_id = OSA_ENOTIPL,
		.m_msg = "Command not implemented.",
	},
	{
		.m_id = OSA_EBADCMD,
		.m_msg = "Command not supported.",
	},
};

/* Generated file osa_status.c ends. */
