
/*
 * osa_status.h
 *
 * This file is automatically generated on Tue Jul 28 12:04:26 2015
 * DO NOT modify this file!
 *
 */

#if !defined (__OSA_STATUS_H)
#define __OSA_STATUS_H

#define OSA_SOK                      (OSA_STATUS_CLASS_GENERAL|OSA_STATUS_TYPE_SUCCESS|0|100)
#define OSA_EFAIL                    (OSA_STATUS_CLASS_GENERAL|OSA_STATUS_TYPE_ERROR  |0|101)
#define OSA_EMEM                     (OSA_STATUS_CLASS_GENERAL|OSA_STATUS_TYPE_ERROR  |0|102)
#define OSA_ENOENT                   (OSA_STATUS_CLASS_GENERAL|OSA_STATUS_TYPE_ERROR  |0|103)
#define OSA_EARGS                    (OSA_STATUS_CLASS_GENERAL|OSA_STATUS_TYPE_ERROR  |0|104)
#define OSA_EINVAL                   (OSA_STATUS_CLASS_GENERAL|OSA_STATUS_TYPE_ERROR  |0|105)
#define OSA_EEXIST                   (OSA_STATUS_CLASS_GENERAL|OSA_STATUS_TYPE_ERROR  |0|106)
#define OSA_ERES                     (OSA_STATUS_CLASS_GENERAL|OSA_STATUS_TYPE_ERROR  |0|107)
#define OSA_EPERM                    (OSA_STATUS_CLASS_GENERAL|OSA_STATUS_TYPE_ERROR  |0|108)
#define OSA_ECONNECT                 (OSA_STATUS_CLASS_NETWORK|OSA_STATUS_TYPE_ERROR  |0|200)
#define OSA_ETIMEOUT                 (OSA_STATUS_CLASS_IO     |OSA_STATUS_TYPE_ERROR  |0|300)
#define OSA_EEOF                     (OSA_STATUS_CLASS_IO     |OSA_STATUS_TYPE_WARNING|0|301)
#define OSA_ENOTIPL                  (OSA_STATUS_CLASS_APP    |OSA_STATUS_TYPE_WARNING|0|600)
#define OSA_EBADCMD                  (OSA_STATUS_CLASS_APP    |OSA_STATUS_TYPE_ERROR  |0|601)

#define OSA_STATUS_DESCP_NUM         14

extern osa_status_descp_t glb_status_descps[OSA_STATUS_DESCP_NUM];

#endif  /* if !defined (__OSA_STATUS_H) */
