
/*
 * vcs_cmds.h
 *
 * This file is automatically generated on Tue Jul 28 15:25:49 2015
 * DO NOT modify this file!
 *
 */

#if !defined (__VCS_CMDS_H)
#define __VCS_CMDS_H

/* Module command codes */

#define IPNC_CMD_LOGON                               100
#define IPNC_CMD_LOGOFF                              101
#define IPNC_CMD_QUIT                                101
#define IPNC_CMD_USERADD                             102
#define IPNC_CMD_USERMOD                             103
#define IPNC_CMD_USERLIST                            104
#define IPNC_CMD_CHANGEPWD                           105
#define IPNC_CMD_USERDEL                             106
#define IPNC_CMD_REBOOT                              200
#define IPNC_CMD_GET_SYSINFO                         201
#define IPNC_CMD_GET_NET_PARAMS                      202
#define IPNC_CMD_SET_NET_PARAMS                      203
#define IPNC_CMD_GET_TEMPERATURE                     204
#define IPNC_CMD_GET_DATETIME                        205
#define IPNC_CMD_SET_DATETIME                        206
#define IPNC_CMD_GET_VOLTAGES                        207
#define IPNC_CMD_GET_COLORBAR                        208
#define IPNC_CMD_SET_COLORBAR                        209
#define IPNC_CMD_GET_PEER_IP                         210
#define IPNC_CMD_GET_JPEGHEADER                      211
#define IPNC_CMD_START_JPEG                          212
#define IPNC_CMD_STOP_JPEG                           213
#define IPNC_CMD_GET_DIMS                            214
#define IPNC_CMD_LIST_STREAMS                        215
#define IPNC_CMD_KILL_STREAM                         216
#define IPNC_CMD_GET_EMBHEADER                       217
#define IPNC_CMD_LOCK_MGR                            218
#define IPNC_CMD_KEEPALIVE                           219
#define IPNC_CMD_GETACCESS                           220
#define IPNC_CMD_GETVAB                              221
#define IPNC_CMD_SETVAB                              222
#define IPNC_CMD_G_TRANS_VOLS                        223
#define IPNC_CMD_S_TRANS_VOLS                        224
#define IPNC_CMD_G_SENSOR_PARAMS                     225
#define IPNC_CMD_S_SENSOR_PARAMS                     226
#define IPNC_CMD_SET_SHUTTTER                        227
#define IPNC_CMD_SET_RAWGAIN                         228
#define IPNC_CMD_SEL_PARAMSET                        229
#define IPNC_CMD_GET_PARAMSET                        230
#define IPNC_CMD_GET_CURRENT_PARAMSET                231
#define IPNC_CMD_GET_NUM_PARAMSETS                   232
#define IPNC_CMD_SET_PARAMSET                        233
#define IPNC_CMD_ENABLE_AUTO_EXP                     234
#define IPNC_CMD_ENABLE_AUTO_WB                      235
#define IPNC_CMD_SET_WB                              236
#define IPNC_CMD_SET_BRIGHTNESS                      237
#define IPNC_CMD_SET_CONTRAST                        238
#define IPNC_CMD_SET_SHARPNESS                       239
#define IPNC_CMD_SET_GLOBAL_GAIN                     240
#define IPNC_CMD_SET_EXP_COMPENSATION                241
#define IPNC_CMD_SET_WB_COMPENSATION                 242
#define IPNC_CMD_SET_ISO                             243
#define IPNC_CMD_SET_GAMMA                           244
#define IPNC_CMD_SET_LM_MODE                         245
#define IPNC_CMD_SET_DARK_CURRENT                    246
#define IPNC_CMD_SET_CODEC_SETTINGS                  247
#define IPNC_CMD_GET_CODEC_SETTINGS                  248
#define IPNC_CMD_DUMP_WORKING_STATUS                 249
#define IPNC_CMD_WRITE_SETTINGS                      250

#define VCS_CMDS_NUMS                                 59

extern osa_cmd_t gbl_vcs_cmds[VCS_CMDS_NUMS];

#define IPNC_CMD_LOGON_ARG_u                           0
#define IPNC_CMD_LOGON_ARG_p                           1
#define IPNC_CMD_USERADD_ARG_u                         0
#define IPNC_CMD_USERADD_ARG_p                         1
#define IPNC_CMD_USERADD_ARG_n                         2
#define IPNC_CMD_USERADD_ARG_a                         3
#define IPNC_CMD_USERMOD_ARG_u                         0
#define IPNC_CMD_USERMOD_ARG_p                         1
#define IPNC_CMD_USERMOD_ARG_n                         2
#define IPNC_CMD_USERMOD_ARG_a                         3
#define IPNC_CMD_CHANGEPWD_ARG_u                       0
#define IPNC_CMD_CHANGEPWD_ARG_p                       1
#define IPNC_CMD_USERDEL_ARG_u                         0
#define IPNC_CMD_SET_NET_PARAMS_ARG_ip                 0
#define IPNC_CMD_SET_NET_PARAMS_ARG_nm                 1
#define IPNC_CMD_SET_NET_PARAMS_ARG_gw                 2
#define IPNC_CMD_SET_NET_PARAMS_ARG_dhcp               3
#define IPNC_CMD_SET_NET_PARAMS_ARG_hn                 4
#define IPNC_CMD_SET_NET_PARAMS_ARG_dns1               5
#define IPNC_CMD_SET_NET_PARAMS_ARG_dns2               6
#define IPNC_CMD_SET_NET_PARAMS_ARG_dns3               7
#define IPNC_CMD_SET_DATETIME_ARG_t                    0
#define IPNC_CMD_SET_COLORBAR_ARG_mode                 0
#define IPNC_CMD_START_JPEG_ARG_ip                     0
#define IPNC_CMD_START_JPEG_ARG_rtp                    1
#define IPNC_CMD_START_JPEG_ARG_rtcp                   2
#define IPNC_CMD_STOP_JPEG_ARG_sid                     0
#define IPNC_CMD_KILL_STREAM_ARG_sid                   0
#define IPNC_CMD_LOCK_MGR_ARG_enabled                  0
#define IPNC_CMD_KEEPALIVE_ARG_sid                     0
#define IPNC_CMD_KEEPALIVE_ARG_ip                      1
#define IPNC_CMD_KEEPALIVE_ARG_rtp                     2
#define IPNC_CMD_KEEPALIVE_ARG_rtcp                    3
#define IPNC_CMD_SETVAB_ARG_vab                        0
#define IPNC_CMD_S_TRANS_VOLS_ARG_vh                   0
#define IPNC_CMD_S_TRANS_VOLS_ARG_vhl                  1
#define IPNC_CMD_S_TRANS_VOLS_ARG_rg                   2
#define IPNC_CMD_S_SENSOR_PARAMS_ARG_sn                0
#define IPNC_CMD_S_SENSOR_PARAMS_ARG_hw_id               1
#define IPNC_CMD_S_SENSOR_PARAMS_ARG_vh                2
#define IPNC_CMD_S_SENSOR_PARAMS_ARG_vhl               3
#define IPNC_CMD_S_SENSOR_PARAMS_ARG_rg                4
#define IPNC_CMD_S_SENSOR_PARAMS_ARG_vab               5
#define IPNC_CMD_S_SENSOR_PARAMS_ARG_debug               6
#define IPNC_CMD_SET_SHUTTTER_ARG_v                    0
#define IPNC_CMD_SET_RAWGAIN_ARG_v                     0
#define IPNC_CMD_SEL_PARAMSET_ARG_v                    0
#define IPNC_CMD_GET_PARAMSET_ARG_idx                  0
#define IPNC_CMD_SET_PARAMSET_ARG_id                   0
#define IPNC_CMD_SET_PARAMSET_ARG_base64               1
#define IPNC_CMD_ENABLE_AUTO_EXP_ARG_en                0
#define IPNC_CMD_ENABLE_AUTO_WB_ARG_en                 0
#define IPNC_CMD_SET_WB_ARG_gain_r                     0
#define IPNC_CMD_SET_WB_ARG_gain_gr                    1
#define IPNC_CMD_SET_WB_ARG_gain_gb                    2
#define IPNC_CMD_SET_WB_ARG_gain_b                     3
#define IPNC_CMD_SET_WB_ARG_offs_r                     4
#define IPNC_CMD_SET_WB_ARG_offs_gr                    5
#define IPNC_CMD_SET_WB_ARG_offs_gb                    6
#define IPNC_CMD_SET_WB_ARG_offs_b                     7
#define IPNC_CMD_SET_BRIGHTNESS_ARG_v                  0
#define IPNC_CMD_SET_CONTRAST_ARG_v                    0
#define IPNC_CMD_SET_SHARPNESS_ARG_v                   0
#define IPNC_CMD_SET_GLOBAL_GAIN_ARG_v                 0
#define IPNC_CMD_SET_EXP_COMPENSATION_ARG_v               0
#define IPNC_CMD_SET_WB_COMPENSATION_ARG_v               0
#define IPNC_CMD_SET_ISO_ARG_v                         0
#define IPNC_CMD_SET_GAMMA_ARG_r                       0
#define IPNC_CMD_SET_GAMMA_ARG_g                       1
#define IPNC_CMD_SET_GAMMA_ARG_b                       2
#define IPNC_CMD_SET_LM_MODE_ARG_mode                  0
#define IPNC_CMD_SET_DARK_CURRENT_ARG_v                0
#define IPNC_CMD_SET_CODEC_SETTINGS_ARG_base64               0

#endif  /* if !defined (__VCS_CMDS_H) */
